kind: Deployment
apiVersion: apps/v1
metadata:
  name: publisher-app
  labels:
    app: publisher-app
    app.kubernetes.io/component: publisher-app
    app.kubernetes.io/instance: publisher-app
    app.kubernetes.io/part-of: rabbitmq-servicebus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher-app
  template:
    metadata:
      labels:
        app: publisher-app
        deploymentconfig: publisher-app
    spec:
      containers:
        - name: publisher-app
          image: >-
            darshanadinushal/rabbitmq-publisher:1.0.0
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  name: publisher-app
  labels:
    app: publisher-app
    app.kubernetes.io/component: publisher-app
    app.kubernetes.io/instance: publisher-app
    app.kubernetes.io/part-of: rabbitmq-servicebus
spec:
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: publisher-app
    deploymentconfig: publisher-app
  type: ClusterIP





